import * as THREE from 'three'
import type { Intersection, IntersectionPort, InternalLane, Crosswalk, StopLine, WaitingArea } from '../../types/intersection'
import type { RoadNetwork, RoadNode, RoadSegment } from '../../types/roadNetwork'
import { uid } from '../../utils/id'
import { getRoadTypeWidth } from '../../types/roadType'
import { leftNormal } from '../../utils/geometry'

export class IntersectionBuilder {
  shouldCreateIntersection(node: RoadNode): boolean { return node.connectedSegmentIds.length >= 3 || node.type === 'intersection' || node.connectedSegmentIds.length === 2 }

  buildIntersectionFromNode(node: RoadNode, network: RoadNetwork): Intersection {
    const segments = node.connectedSegmentIds.map(id => network.segments.find(s => s.id === id)).filter(Boolean) as RoadSegment[]
    const ports = this.computeIntersectionPorts(node, segments, network)
    const sorted = this.sortPortsByAngle(ports, node.position)
    return {
      id: uid('intersection'), nodeId: node.id, connectedSegmentIds: segments.map(s => s.id),
      boundary: this.buildIntersectionBoundary(sorted, node.position), ports: sorted,
      internalLaneConnections: this.buildInternalLaneConnections(sorted, node.position),
      crosswalks: this.buildCrosswalks(sorted, node.position), stopLines: this.buildStopLines(sorted, node.position),
      waitingAreas: this.buildWaitingAreas(sorted, node.position), islands: [], autoGenerated: true
    }
  }

  computeIntersectionPorts(node: RoadNode, segments: RoadSegment[], network: RoadNetwork): IntersectionPort[] {
    return segments.map(segment => {
      const otherId = segment.startNodeId === node.id ? segment.endNodeId : segment.startNodeId
      const other = network.nodes.find(n => n.id === otherId)!
      const tangent = other.position.clone().sub(node.position).setY(0).normalize()
      const normal = leftNormal(tangent)
      const rt = network.roadTypes.find(t => t.id === segment.roadTypeId)!
      const half = getRoadTypeWidth(rt) / 2
      return { id: uid('port'), segmentId: segment.id, position: node.position.clone(), tangent, leftEdge: node.position.clone().add(normal.clone().multiplyScalar(half)), rightEdge: node.position.clone().add(normal.clone().multiplyScalar(-half)), lanePortIds: [] }
    })
  }

  sortPortsByAngle(ports: IntersectionPort[], center: THREE.Vector3): IntersectionPort[] {
    return [...ports].sort((a,b)=>Math.atan2(a.tangent.z,a.tangent.x)-Math.atan2(b.tangent.z,b.tangent.x))
  }

  buildIntersectionBoundary(ports: IntersectionPort[], center: THREE.Vector3): THREE.Vector3[] {
    const pts: THREE.Vector3[] = []
    for (const p of ports) { pts.push(p.leftEdge.clone().add(p.tangent.clone().multiplyScalar(5))); pts.push(p.rightEdge.clone().add(p.tangent.clone().multiplyScalar(5))) }
    return pts.length >= 3 ? pts : [center.clone().add(new THREE.Vector3(-5,0,-5)), center.clone().add(new THREE.Vector3(5,0,-5)), center.clone().add(new THREE.Vector3(5,0,5)), center.clone().add(new THREE.Vector3(-5,0,5))]
  }

  trimConnectedSegments() {}

  buildInternalLaneConnections(ports: IntersectionPort[], center: THREE.Vector3): InternalLane[] {
    const lanes: InternalLane[] = []
    for (const a of ports) for (const b of ports) if (a.id !== b.id) {
      const turn = a.tangent.clone().cross(b.tangent).y > 0.2 ? 'left' : a.tangent.dot(b.tangent) < -0.5 ? 'straight' : 'right'
      const p0 = center.clone().add(a.tangent.clone().multiplyScalar(6))
      const p2 = center.clone().add(b.tangent.clone().multiplyScalar(6))
      lanes.push({ id: uid('internalLane'), fromPortId: a.id, toPortId: b.id, turn, path: [p0, center.clone(), p2], polygon: [] })
    }
    return lanes
  }

  buildCrosswalks(ports: IntersectionPort[], center: THREE.Vector3): Crosswalk[] { return ports.map(p => ({ id: uid('crosswalk'), points: [p.leftEdge.clone().add(p.tangent.clone().multiplyScalar(7)), p.rightEdge.clone().add(p.tangent.clone().multiplyScalar(7))], width: 3 })) }
  buildStopLines(ports: IntersectionPort[], center: THREE.Vector3): StopLine[] { return ports.map(p => ({ id: uid('stopLine'), points: [p.leftEdge.clone().add(p.tangent.clone().multiplyScalar(9)), p.rightEdge.clone().add(p.tangent.clone().multiplyScalar(9))] })) }
  buildWaitingAreas(ports: IntersectionPort[], center: THREE.Vector3): WaitingArea[] { return ports.filter((_,i)=>i%2===0).map(p => ({ id: uid('waiting'), polygon: [center.clone(), center.clone().add(p.tangent.clone().multiplyScalar(4)), center.clone().add(p.tangent.clone().multiplyScalar(4)).add(leftNormal(p.tangent).multiplyScalar(2))] })) }
}
