import type { Vector3 } from 'three'
export interface IntersectionPort { id: string; segmentId: string; position: Vector3; tangent: Vector3; leftEdge: Vector3; rightEdge: Vector3; lanePortIds: string[] }
export interface InternalLane { id: string; fromPortId: string; toPortId: string; turn: 'straight' | 'left' | 'right' | 'uturn'; path: Vector3[]; polygon: Vector3[] }
export interface Crosswalk { id: string; points: Vector3[]; width: number }
export interface StopLine { id: string; points: Vector3[] }
export interface WaitingArea { id: string; polygon: Vector3[] }
export interface TrafficIsland { id: string; polygon: Vector3[] }
export interface Intersection { id: string; nodeId: string; connectedSegmentIds: string[]; boundary: Vector3[]; ports: IntersectionPort[]; internalLaneConnections: InternalLane[]; crosswalks: Crosswalk[]; stopLines: StopLine[]; waitingAreas: WaitingArea[]; islands: TrafficIsland[]; autoGenerated: boolean }
