import type { Vector3 } from 'three'
import type { RoadType } from './roadType'
import type { RoadMarking } from './marking'
import type { TrafficSign } from './sign'
import type { Intersection } from './intersection'
export interface Lane { id: string; index: number; direction: 'forward' | 'backward'; width: number; centerOffset: number; allowedTurns: Array<'straight' | 'left' | 'right' | 'uturn'> }
export interface RoadNode { id: string; position: Vector3; type: 'endpoint' | 'junction' | 'intersection' | 'virtual'; connectedSegmentIds: string[]; radius: number; elevation: number; autoGenerated: boolean }
export interface RoadSegment { id: string; startNodeId: string; endNodeId: string; controlPoints: Vector3[]; roadTypeId: string; curveType: 'straight' | 'bezier' | 'catmullRom'; length: number; forwardLanes: Lane[]; backwardLanes: Lane[]; width: number; elevationMode: 'ground' | 'elevated' | 'bridge' | 'tunnel'; markings: RoadMarking[]; signs: TrafficSign[] }
export interface LaneConnection { id: string; fromSegmentId: string; toSegmentId: string; fromLaneId: string; toLaneId: string; path: Vector3[] }
export interface RoadNetwork { nodes: RoadNode[]; segments: RoadSegment[]; intersections: Intersection[]; roadTypes: RoadType[]; laneConnections: LaneConnection[] }
