import type { RoadType } from '../../types/roadType'
export function createDefaultRoadTypes(): RoadType[] {
  return [
    { id:'two_lane', name:'双向两车道', category:'urban', forwardLaneCount:1, backwardLaneCount:1, laneWidth:3.5, hasMedian:false, medianWidth:0, hasSidewalk:true, sidewalkWidth:2, hasGreenBelt:false, greenBeltWidth:0, speedLimit:40, allowedTurns:['straight','left','right'], defaultMarkingStyle:'dashed', material:{surfaceColor:0x333842, edgeColor:0x596171, markingColor:0xf7f2d0}},
    { id:'four_lane', name:'双向四车道', category:'urban', forwardLaneCount:2, backwardLaneCount:2, laneWidth:3.5, hasMedian:false, medianWidth:0, hasSidewalk:true, sidewalkWidth:2.5, hasGreenBelt:false, greenBeltWidth:0, speedLimit:50, allowedTurns:['straight','left','right'], defaultMarkingStyle:'dashed', material:{surfaceColor:0x303640, edgeColor:0x5a6575, markingColor:0xf7f2d0}},
    { id:'arterial_median', name:'城市主干道/中央隔离', category:'urban', forwardLaneCount:3, backwardLaneCount:3, laneWidth:3.5, hasMedian:true, medianWidth:3, hasSidewalk:true, sidewalkWidth:3, hasGreenBelt:true, greenBeltWidth:1.5, speedLimit:60, allowedTurns:['straight','left','right','uturn'], defaultMarkingStyle:'solid', material:{surfaceColor:0x2d333d, edgeColor:0x627184, markingColor:0xffffff}},
    { id:'one_way', name:'单向两车道', category:'urban', forwardLaneCount:2, backwardLaneCount:0, laneWidth:3.4, hasMedian:false, medianWidth:0, hasSidewalk:true, sidewalkWidth:2, hasGreenBelt:false, greenBeltWidth:0, speedLimit:45, allowedTurns:['straight','left','right'], defaultMarkingStyle:'dashed', material:{surfaceColor:0x343a43, edgeColor:0x596171, markingColor:0xffffff}},
    { id:'ramp', name:'匝道', category:'ramp', forwardLaneCount:1, backwardLaneCount:0, laneWidth:4, hasMedian:false, medianWidth:0, hasSidewalk:false, sidewalkWidth:0, hasGreenBelt:false, greenBeltWidth:0, speedLimit:40, allowedTurns:['straight','right'], defaultMarkingStyle:'solid', material:{surfaceColor:0x29313a, edgeColor:0x525d68, markingColor:0xffffff}},
    { id:'pedestrian', name:'人行道路', category:'pedestrian', forwardLaneCount:0, backwardLaneCount:0, laneWidth:0, hasMedian:false, medianWidth:0, hasSidewalk:true, sidewalkWidth:4, hasGreenBelt:false, greenBeltWidth:0, speedLimit:8, allowedTurns:['straight'], defaultMarkingStyle:'none', material:{surfaceColor:0x6e6252, edgeColor:0x827766, markingColor:0xffffff}}
  ]
}
